apiVersion: v1
kind: Pod
metadata:
  name: storage1
  namespace: release
  labels:
    app: storage1
spec:
  containers:
    - name: writer
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo Hello from writer > /data/message.txt && sleep 3600"]
      volumeMounts:
        - name: shared-data
          mountPath: /data

    - name: reader
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 5 && cat /data/message.txt && sleep 3600"]
      volumeMounts:
        - name: shared-data
          mountPath: /data

  volumes:
    - name: shared-data
      emptyDir: {}